### ISSUE TITLE
Add SassDoc for easy documenting on the framework.

### ISSUE THREAD

**Issue by WMontagnon** [Qarzak/nuCSS#15]
Let's add SassDoc (https://github.com/SassDoc/sassdoc) in order to bring an easy way to generate docs for the nuCSS framework.

**Comment by danmurf** [comment]
Hi, I'd like to have a go at helping with this. I've just tried to run the SCSS directory through SassDoc, but SassDoc (from what I can tell) only works with Sass, not Scss. Apologies if there is something obvious I'm missing here.

**Comment by WMontagnon** [comment]
I got it to work by adding a gulp task (http://sassdoc.com/gulp/) and a comment on the grid mixin.

What error did you have ?

**Comment by danmurf** [comment]
[WARNING] SassDoc could not find anything to document.

**Comment by WMontagnon** [comment]
Yeah, ok. I got this too, which is not really an error.

SassDoc is using comments (http://sassdoc.com/annotations/) to generate the documentation, and in your case it didn't find any. Try adding one in any .scss file and you should be ok.

For now there isn't so many things to document, except the grid system and media queries. I guess you can start with those until we add some new components.

Thanks for your help anyway ;)

**Comment by WMontagnon** [comment]
But the first thing to do I think is to add a gulp task, which could be run on build.

I've tried with this one, but I think we can make some improvements :
`gulp.task('sassdoc', function () {  
   return gulp.src('assets/scss/**/*.scss')
     .pipe($.sassdoc());
 });`

**Comment by danmurf** [comment]
Super! I've got it working as you've suggested. I've created a separate sassdoc.js for the sassdoc settings, and added some extra options. Are you OK for me to submit a pull request for this? https://github.com/danmurf/nuCSS/tree/feature/sassdoc

**Comment by WMontagnon** [comment]
Great job you've done here ! 

Just one thing though, I think it might be better if the `/doc` folder was ignored by git, and the sassdoc task run in the build task (set in the gulpfile) which is fired on the `npm install`. 

What do you think about this ?

**Comment by danmurf** [comment]
Good idea. I'll git ignore the `/doc` folder. I've also set the sassdoc task to run in the build task.

**Comment by WMontagnon** [comment]
That's great ! Thanks for your input on this project.

Don't hesitate to jump on other issues, or even create one if you think something could be added to this project.

**Comment by danmurf** [comment]
You're welcome and thanks your help :)
