### ISSUE TITLE
Add editorconfig file to project

### ISSUE THREAD

**Issue by code4cake** [Qarzak/nuCSS#20]
# This helps developers define and maintain consistent coding styles between different editors and IDEs. Please ensure your editor is set up to use the .editorconfig file. For more information, check out [editorconfig](http://editorconfig.org/)

**Comment by WMontagnon** [comment]
Hey, this sounds like a great idea. 
I didn't know about this .editorconfig file but it seems like something we should add.

Go ahead and make a PR for this.
