### ISSUE TITLE
Base typography styles.

### ISSUE THREAD

**Issue by WMontagnon** [Qarzak/nuCSS#7]
Create base styles for:
- [ ] Headings
- [ ] Paragraphs
- [ ] Unordered lists
- [ ] Ordered lists
- [ ] Blockquotes
- [ ] Code
- [ ] Links

**Comment by code4cake** [comment]
I'll take this is no one is working on it

**Comment by WMontagnon** [comment]
You can go ahead, and don't hesitate do ask any questions.

**Comment by code4cake** [comment]
Thanks man. May I  divide the stylesheets into components?

```
styles
|
abstract
    |
    _mixins.scss
    |
    _variables.scss   # Global variables
|
base
    |
    _base.scss        # Base / global declarations
    |
    _typography.scss  # h1 h2 => p declarations
|
components
    |
        _button.scss
...
```

**Comment by WMontagnon** [comment]
It's already done, under `/lib/scss`.

The base folder doesn't exist for now though, might be a good idea to add it.

**Comment by WMontagnon** [comment]
I don't know if you're still working on it, but I think you should know I made big changes to the project's architecture. Might be a good idea to pull this.

**Comment by code4cake** [comment]
Hey man shit yes. I'm actually almost done. I was doing the blockquotes and the code part now. I had also moved around the architecture a bit. 

I will go ahead and push the branch I have so you can take a look and pull from yours

**Comment by WMontagnon** [comment]
Glad to hear that, can't wait to try out what you've done !

**Comment by code4cake** [comment]
Hey man just sent you a PR, if the excessive  modularization of the `scss` is a bit too much let me know and I'll rework it.

**Comment by WMontagnon** [comment]
Nice.

I've starting reviewing it, i'll let you know soon what I'm thinking about it. Thanks for your input.
